#ifndef ENGINE_DISPLAY_IGENERICANIMATION_H
#define ENGINE_DISPLAY_IGENERICANIMATION_H

namespace DKDSP {

enum EANIMATIONTYPE {
    ANIMATION_TYPE_ANM,
    ANIMATION_TYPE_DMA,
    ANIMATION_TYPE_TAN,
    ANIMATION_TYPE_EVN,
    ANIMATION_TYPE_4,
};

// TODO
class IGenericAnimation {
public:
    virtual EANIMATIONTYPE GetType() = 0;
};

}

#endif
